Repository typedb/typeql, pull requests merged in 2019-09, with the labels that each got.

#78 GraqlDelete Ignore limit filter
  java/parser/Parser.java
Labels: bug

#79 Adapt to latest @graknlabs_bazel_distribution
  WORKSPACE
Labels: bug, build

#80 Use Github credential for release-cleanup
  .circleci/config.yml
Labels: build

#81 Add release title in the Github draft
  BUILD
Labels: build
