Repository typedb/typeql, pull requests merged in 2019-04, with the labels that each got.

#29 Ignore null in Graql Aggregate Hashcode
  java/query/GraqlGet.java
Labels: bug

#30 Fix aggregate hashcodes
  java/query/GraqlGet.java
Labels: bug

#54 Rename to asRetrievedVar() and isRetrieved
  java/property/HasAttributeProperty.java
  java/statement/Statement.java
  java/statement/Variable.java
Labels: refactor

#59 Extended label lexer
  grammar/Graql.g4
Labels: feature

#60 Restrict the token patterns for type labels and ID values
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
  grammar/BUILD
  grammar/Graql.g4
  java/BUILD
  java/parser/Parser.java
  java/parser/test/ParserTest.java
  java/property/TypeProperty.java
  java/query/GraqlCompute.java
  java/query/test/GraqlQueryTest.java
  java/statement/Statement.java
  java/util/StringUtil.java
Labels: refactor
