Repository typedb/typeql, pull requests merged in 2019-10, with the labels that each got.

#82 Adapt to latest changes in bazel-distribution
  .circleci/config.yml
  grammar/BUILD
  java/BUILD
Labels: bug, build

#83 Refactor how version is provided to deployment rules
  .circleci/config.yml
  BUILD
Labels: build, refactor

#84 Migrate utils to graknlabs/common
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
  java/BUILD
  java/parser/Parser.java
  java/parser/test/BUILD
  java/parser/test/ParserTest.java
  java/pattern/Disjunction.java
  java/pattern/test/BUILD
  java/pattern/test/PatternTest.java
  java/query/GraqlCompute.java
  java/query/test/BUILD
  java/query/test/GraqlDeleteTest.java
  java/query/test/GraqlInsertTest.java
  java/util/Collections.java
  java/util/Triple.java
  java/util/Tuple.java
Labels: refactor

#85 Remove special Compute Count Attribute Exclusion
  java/query/GraqlCompute.java
Labels: refactor

#86 Integrate checking for unused Java dependencies
  .circleci/config.yml
  WORKSPACE
Labels: build, feature
