Repository typedb/typeql, pull requests merged in 2019-02, with the labels that each got.

#7 Moved Token to Grakn.Token
  java/Graql.java
  java/exception/GraqlException.java
  java/parser/Parser.java
  java/parser/test/ParserTest.java
  java/pattern/Conjunction.java
  java/pattern/Disjunction.java
  java/pattern/Negation.java
  java/property/AbstractProperty.java
  java/property/DataTypeProperty.java
  java/property/HasAttributeProperty.java
  java/property/HasAttributeTypeProperty.java
  java/property/IdProperty.java
  java/property/IsaProperty.java
  java/property/NeqProperty.java
  java/property/PlaysProperty.java
  java/property/RegexProperty.java
  java/property/RelatesProperty.java
  java/property/RelationProperty.java
  java/property/SubProperty.java
  java/property/ThenProperty.java
  java/property/TypeProperty.java
  java/property/ValueProperty.java
  java/property/WhenProperty.java
  java/query/GraqlCompute.java
  java/query/GraqlDefine.java
  java/query/GraqlDelete.java
  java/query/GraqlGet.java
  java/query/GraqlInsert.java
  java/query/GraqlUndefine.java
  java/query/MatchClause.java
  java/query/builder/Aggregatable.java
  java/query/builder/Computable.java
  java/query/builder/Filterable.java
  java/query/test/GraqlQueryTest.java
  java/statement/Statement.java
  java/statement/StatementInstance.java
  java/statement/StatementThing.java
  java/statement/StatementType.java
  java/statement/Variable.java
  java/statement/builder/StatementAttributeBuilder.java
  java/statement/builder/StatementTypeBuilder.java
  java/util/Token.java
Labels: refactor

#9 Enable RBE
  .bazelrc
Labels: build

#11 Added Bazel rules for Maven deployment
  dependencies/maven/rules.bzl
  deployment.properties
  java/BUILD
Labels: build

#13 Improved Parser.parseQuery()
  grammar/Graql.g4
  java/parser/Parser.java
  java/parser/test/ParserTest.java
Labels: refactor

#14 GraqlGet subqueries enforces variables to within scope
  java/exception/ErrorMessage.java
  java/query/GraqlGet.java
Labels: bug

#17 Introducing 'native types' in Graql grammar and tokens
  grammar/Graql.g4
  java/Graql.java
  java/parser/Parser.java
  java/property/RelationProperty.java
  java/util/StringUtil.java
Labels: feature, refactor

#18 Overloaded Statement.sub() and .isa() to accept Graql.Token.Type
  java/statement/builder/StatementInstanceBuilder.java
  java/statement/builder/StatementTypeBuilder.java
Labels: feature, refactor

#20 Overloaded Graql.type() to accept Graql.Token.Type
  java/Graql.java
Labels: feature, refactor

#22 Refined String-escaping behaviour
  dependencies/maven/artifacts/commons-lang/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
  grammar/Graql.g4
  java/BUILD
  java/parser/Parser.java
  java/parser/SyntaxError.java
  java/parser/test/ParserTest.java
  java/pattern/Disjunction.java
  java/pattern/Pattern.java
  java/property/RegexProperty.java
  java/property/ValueProperty.java
  java/query/test/GraqlQueryTest.java
  java/util/StringUtil.java
Labels: bug, refactor
