Repository typedb/typeql, pull requests merged in 2020-11, with the labels that each got.

#170 Correct Parsing and Validation for Attributes constraints
  dependencies/graknlabs/repositories.bzl
  grammar/Graql.g4
  java/common/exception/ErrorMessage.java
  java/parser/Parser.java
  java/pattern/constraint/ThingConstraint.java
  java/pattern/schema/Rule.java
Labels: type: feature

#171 Fixed parsing of played-role overriding, and printing of overridden types
  java/parser/Parser.java
  java/parser/test/ParserTest.java
  java/pattern/constraint/TypeConstraint.java
Labels: type: bug

#172 Reference.Name extendable in Grakn Core
  java/common/GraqlToken.java
  java/pattern/variable/Reference.java
Labels: type: feature

#173 Make Maven release depend on GitHub deployment
  .grabl/automation.yml
Labels: type: build
