Repository typedb/typeql, pull requests merged in 2020-06, with the labels that each got.

#127 Remove implicit types syntax from grammar
  grammar/Graql.g4
  java/Graql.java
  java/parser/Parser.java
  java/parser/test/ParserTest.java
  java/property/HasAttributeProperty.java
  java/property/HasAttributeTypeProperty.java
  java/statement/builder/StatementInstanceBuilder.java
Labels: type: refactor

#133 Use Ubuntu 16 Image and update build tools
  .circleci/config.yml
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
Labels: priority: high, type: build

#135 Depend on @graknlabs_dependencies
  .bazelrc
  .circleci/config.yml
  WORKSPACE
  dependencies/compilers/BUILD
  dependencies/compilers/dependencies.bzl
  dependencies/graknlabs/dependencies.bzl
  dependencies/maven/BUILD
  dependencies/maven/artifacts.bzl
  dependencies/maven/artifacts/com/google/code/findbugs/BUILD
  dependencies/maven/artifacts/com/google/errorprone/BUILD
  dependencies/maven/artifacts/com/google/guava/BUILD
  dependencies/maven/artifacts/com/google/j2objc/BUILD
  dependencies/maven/artifacts/org/antlr/BUILD
  dependencies/maven/artifacts/org/codehaus/mojo/BUILD
  dependencies/maven/artifacts/org/hamcrest/BUILD
  dependencies/maven/artifacts/org/slf4j/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
  dependencies/maven/update.sh
  grammar/BUILD
  java/BUILD
  java/parser/test/BUILD
  java/pattern/test/BUILD
  java/query/test/BUILD
Labels: type: build

#140 Add labels and scoped roles to the grammar and parsers
  grammar/Graql.g4
  java/Graql.java
  java/parser/Parser.java
  java/parser/test/ParserTest.java
  java/property/TypeProperty.java
  java/query/GraqlCompute.java
  java/query/builder/Computable.java
  java/statement/Label.java
  java/statement/Statement.java
  java/statement/builder/StatementTypeBuilder.java
Labels: priority: high, type: feature, type: refactor
