Repository typedb/typeql, pull requests merged in 2020-10, with the labels that each got.

#160 Implement rules for Graql 2.0
  dependencies/graknlabs/repositories.bzl
  grammar/Graql.g4
  java/Graql.java
  java/common/GraqlToken.java
  java/common/exception/ErrorMessage.java
  java/parser/Parser.java
  java/parser/test/ParserTest.java
  java/pattern/BUILD
  java/pattern/Conjunction.java
  java/pattern/Definable.java
  java/pattern/Disjunction.java
  java/pattern/constraint/TypeConstraint.java
  java/pattern/schema/Rule.java
  java/pattern/variable/TypeVariable.java
  java/pattern/variable/UnboundVariable.java
  java/pattern/variable/builder/TypeVariableBuilder.java
  java/query/GraqlDefinable.java
  java/query/GraqlDefine.java
  java/query/GraqlUndefine.java
  java/query/test/GraqlQueryTest.java
  java/test/behaviour/graql/GraqlSteps.java
  java/test/deployment/src/test/java/MavenApplicationTest.java
Labels: priority: high, type: feature

#161 Validate rule 'then' has one constraint and expose Rule state
  java/common/exception/ErrorMessage.java
  java/pattern/schema/Rule.java
Labels: priority: high, type: refactor

#162 Rules are Immutable
  grammar/Graql.g4
  java/parser/Parser.java
  java/pattern/schema/Rule.java
  java/query/test/GraqlQueryTest.java
Labels: priority: high, type: refactor

#166 Add normalisation tests for Disjunction and Negated sub-query
  java/pattern/test/BUILD
  java/pattern/test/NormalisationTest.java
  java/pattern/variable/ThingVariable.java
Labels: type: bug, type: refactor

#168 Refactor Graql Predicates and Concept Equality
  dependencies/graknlabs/repositories.bzl
  grammar/Graql.g4
  java/Graql.java
  java/common/GraqlToken.java
  java/parser/Parser.java
  java/parser/test/ParserTest.java
  java/pattern/Definable.java
  java/pattern/constraint/ThingConstraint.java
  java/pattern/constraint/ValueConstraint.java
  java/pattern/constraint/ValueOperation.java
  java/pattern/variable/ThingVariable.java
  java/pattern/variable/UnboundVariable.java
  java/pattern/variable/builder/ThingVariableBuilder.java
  java/query/GraqlDefinable.java
  java/query/GraqlMatch.java
  java/query/test/GraqlQueryTest.java
  java/test/behaviour/debug/BUILD
  java/test/behaviour/graql/BUILD
  java/test/deployment/src/test/java/MavenApplicationTest.java
Labels: type: feature, type: refactor
