Repository typedb/typeql, pull requests merged in 2021-01, with the labels that each got.

#180 Update grabl automation yaml syntax
  .grabl/automation.yml
Labels: type: build

#184 Fixed Referable Class Typo
  java/pattern/variable/Reference.java
Labels: type: refactor

#182 Update automation.yml to include `release` dependencies
  .grabl/automation.yml
Labels: priority: medium, type: build, type: feature

#186 Refactor exception handling
  java/common/GraqlToken.java
  java/common/exception/ErrorMessage.java
  java/parser/Parser.java
  java/query/GraqlMatch.java
  java/query/builder/Sortable.java
Labels: priority: high, type: bug

#189 Fix the checkstyle error in grabl correctness test
  java/parser/Parser.java
Labels: priority: blocker, priority: low, type: bug

#190 Scope unscoped role types in Plays TypeConstraints
  dependencies/graknlabs/repositories.bzl
  java/pattern/constraint/TypeConstraint.java
Labels: priority: high

#194 Reenable remote build caching
  .bazelrc
  .grabl/automation.yml
Labels: type: build

#195 Mark Isa constraints derived via has constraints as derived
  java/pattern/constraint/ThingConstraint.java
Labels: priority: high, type: feature
