Repository typedb/typeql, pull requests merged in 2022-10, with the labels that each got.

#233 Split delete_or_update in the grammar into separate parser rules
  grammar/TypeQL.g4
  java/parser/Parser.java
  rust/parser/mod.rs
Labels: type: refactor, priority: medium

#239 Introduce unformatted toString
  java/pattern/Conjunction.java
  java/pattern/Definable.java
  java/pattern/Disjunction.java
  java/pattern/Negation.java
  java/pattern/Pattern.java
  java/pattern/schema/Rule.java
  java/pattern/variable/ConceptVariable.java
  java/pattern/variable/ThingVariable.java
  java/pattern/variable/TypeVariable.java
  java/pattern/variable/UnboundVariable.java
  java/pattern/variable/Variable.java
  java/query/TypeQLDefinable.java
  java/query/TypeQLMatch.java
  java/query/TypeQLQuery.java
  java/query/TypeQLUpdate.java
  java/query/TypeQLWritable.java
Labels: type: refactor, priority: blocker

#238 Remove error propagation and force error handling as early as possible
  rust/builder/mod.rs
  rust/parser/mod.rs
  rust/parser/test/mod.rs
  rust/pattern/conjunction.rs
  rust/pattern/constraint/thing/has.rs
  rust/pattern/constraint/thing/isa.rs
  rust/pattern/constraint/thing/relation.rs
  rust/pattern/constraint/type_/owns.rs
  rust/pattern/constraint/type_/plays.rs
  rust/pattern/constraint/type_/relates.rs
  rust/pattern/constraint/type_/sub.rs
  rust/pattern/label.rs
  rust/pattern/negation.rs
  rust/pattern/variable/builder/concept.rs
  rust/pattern/variable/builder/thing.rs
  rust/pattern/variable/builder/type_.rs
  rust/query/mod.rs
  rust/query/typeql_delete.rs
  rust/query/typeql_insert.rs
  rust/query/typeql_match.rs
  rust/query/typeql_update.rs
  rust/query/writable.rs
  rust/util/mod.rs
Labels: type: refactor, priority: medium

#244 Migrate to Factory
  .factory/automation.yml
  README.md
  dependencies/vaticle/repositories.bzl
Labels: type: build, dependencies
