Repository typedb/typeql, pull requests merged in 2022-11, with the labels that each got.

#245 Rust code style refactor
  rust/builder/mod.rs
  rust/parser/mod.rs
  rust/parser/test/mod.rs
  rust/pattern/conjunction.rs
  rust/pattern/constraint/concept.rs
  rust/pattern/constraint/mod.rs
  rust/pattern/constraint/thing/has.rs
  rust/pattern/constraint/thing/iid.rs
  rust/pattern/constraint/thing/isa.rs
  rust/pattern/constraint/thing/mod.rs
  rust/pattern/constraint/thing/relation.rs
  rust/pattern/constraint/thing/value.rs
  rust/pattern/constraint/type_/abstract_.rs
  rust/pattern/constraint/type_/label.rs
  rust/pattern/constraint/type_/mod.rs
  rust/pattern/constraint/type_/owns.rs
  rust/pattern/constraint/type_/plays.rs
  rust/pattern/constraint/type_/regex.rs
  rust/pattern/constraint/type_/relates.rs
  rust/pattern/constraint/type_/sub.rs
  rust/pattern/constraint/type_/value_type.rs
  rust/pattern/disjunction.rs
  rust/pattern/label.rs
  rust/pattern/mod.rs
  rust/pattern/negation.rs
  rust/pattern/schema/mod.rs
  rust/pattern/schema/rule.rs
  rust/pattern/variable/builder/concept.rs
  rust/pattern/variable/builder/mod.rs
  rust/pattern/variable/builder/thing.rs
  rust/pattern/variable/builder/type_.rs
  rust/pattern/variable/concept.rs
  rust/pattern/variable/mod.rs
  rust/pattern/variable/thing.rs
  rust/pattern/variable/type_.rs
  rust/pattern/variable/unbound.rs
  rust/query/aggregate.rs
  rust/query/mod.rs
  rust/query/typeql_define.rs
  rust/query/typeql_delete.rs
  rust/query/typeql_insert.rs
  rust/query/typeql_match.rs
  rust/query/typeql_match_group.rs
  rust/query/typeql_undefine.rs
  rust/query/typeql_update.rs
  rust/query/writable.rs
  rust/typeql_lang.rs
  rust/util/mod.rs
Labels: type: refactor, priority: low

#248 Bump dependencies and python version for GitHub deployment
  .factory/automation.yml
  dependencies/vaticle/repositories.bzl
Labels: type: build, priority: blocker, dependencies

#247 Add Rust IDE sync tool
  .gitignore
  BUILD
  dependencies/ide/rust/BUILD
  dependencies/ide/rust/sync.sh
  dependencies/vaticle/repositories.bzl
Labels: type: refactor, priority: high

#246 Enable disjunctions in rules
  dependencies/vaticle/repositories.bzl
  java/common/exception/ErrorMessage.java
  java/pattern/schema/Rule.java
Labels: type: feature

#250 Add transitive Rust deps that aren't included by default on M1 Macs
  dependencies/vaticle/repositories.bzl
  rust/BUILD
Labels: type: refactor, priority: high

#251 Delete Rust dependencies that were added to patch issue building on M1 Macs
  dependencies/vaticle/repositories.bzl
  rust/BUILD
Labels: type: refactor, priority: high

#253 Regex validation
  dependencies/vaticle/repositories.bzl
  rust/BUILD
  rust/pattern/constraint/type_/mod.rs
  rust/pattern/constraint/type_/regex.rs
Labels: type: feature, priority: high

#255 Migrate TypeQL rust to use pest for parsing
  dependencies/vaticle/repositories.bzl
  grammar/rust/BUILD
  rust/BUILD
  rust/common/error.rs
  rust/parser/error_listener.rs
  rust/parser/mod.rs
  rust/parser/syntax_error.rs
  rust/parser/test/mod.rs
  rust/parser/typeql.pest
  rust/typeql_lang.rs
Labels: type: refactor, priority: high

#257 Pattern normalisation
  dependencies/vaticle/repositories.bzl
  rust/BUILD
  rust/common/error.rs
  rust/common/token.rs
  rust/parser/mod.rs
  rust/parser/test/mod.rs
  rust/parser/typeql.pest
  rust/pattern/conjunction.rs
  rust/pattern/constraint/mod.rs
  rust/pattern/constraint/type_/sub.rs
  rust/pattern/disjunction.rs
  rust/pattern/mod.rs
  rust/pattern/negation.rs
  rust/pattern/test/mod.rs
  rust/pattern/variable/mod.rs
  rust/query/mod.rs
  rust/query/typeql_define.rs
  rust/query/typeql_match.rs
  rust/query/typeql_undefine.rs
  rust/util/mod.rs
Labels: type: feature, priority: high
