Repository typedb/typeql, pull requests merged in 2022-09, with the labels that each got.

#227 Rule conclusion must explicitly specify role types
  java/common/exception/ErrorMessage.java
  java/pattern/schema/Rule.java
Labels: type: bug

#229 Bump typedb-common dependency
  dependencies/vaticle/repositories.bzl
Labels: dependencies

#226 Remove obsolete tests
  java/parser/test/ParserTest.java
Labels: type: refactor, priority: low

#225 TypeQL Rust prototype
  .grabl/automation.yml
  WORKSPACE
  dependencies/vaticle/repositories.bzl
  rust/BUILD
  rust/common/error.rs
  rust/common/mod.rs
  rust/parser/error_listener.rs
  rust/parser/mod.rs
  rust/parser/syntax_error.rs
  rust/parser/test/mod.rs
  rust/pattern/conjunction.rs
  rust/pattern/constraint/mod.rs
  rust/pattern/constraint/thing_constraint.rs
  rust/pattern/constraint/type_constraint.rs
  rust/pattern/mod.rs
  rust/pattern/test/mod.rs
  rust/pattern/variable/builder/mod.rs
  rust/pattern/variable/builder/thing_variable_builder.rs
  rust/pattern/variable/builder/type_variable_builder.rs
  rust/pattern/variable/mod.rs
  rust/pattern/variable/reference.rs
  rust/pattern/variable/thing_variable.rs
  rust/pattern/variable/type_variable.rs
  rust/pattern/variable/unbound_variable.rs
  rust/query/mod.rs
  rust/query/typeql_match.rs
  rust/rustfmt.toml
  rust/typeql_lang.rs
  rust/util/mod.rs
Labels: type: feature, priority: high
