Repository typedb/typeql, pull requests merged in 2023-06, with the labels that each got.

#287 Fix Rust parser for definables and variables
  rust/parser/mod.rs
  rust/parser/test/mod.rs
Labels: type: bug, priority: high

#286 Debug formatting Errors
  rust/common/error/macros.rs
Labels: type: feature, priority: medium

#289 Implement common error traits for Error
  rust/common/error/mod.rs
Labels: type: bug, priority: medium
