Repository typedb/typeql, pull requests merged in 2023-05, with the labels that each got.

#273 Introduce unique annotation
  grammar/TypeQL.g4
  java/common/TypeQLToken.java
  java/common/exception/ErrorMessage.java
  java/parser/Parser.java
  java/parser/test/ParserTest.java
  java/pattern/constraint/TypeConstraint.java
  java/pattern/variable/builder/TypeVariableBuilder.java
Labels: type: feature, priority: high

#283 Remove unnecessary parentheses
  rust/query/typeql_match.rs
Labels: type: refactor, priority: low

#280 Update release notes workflow
  .factory/automation.yml
  BUILD
  LATEST_RELEASE_NOTES.md
  dependencies/vaticle/repositories.bzl
  java/BUILD
  rust/BUILD
  tool/ide/rust/BUILD
  tool/ide/rust/sync.sh
  tool/release/BUILD
  tool/release/create_notes.sh
Labels: priority: high, type: documentation

#282 Implement unique annotation in TypeQL Rust
  rust/builder/mod.rs
  rust/common/string.rs
  rust/common/token.rs
  rust/parser/mod.rs
  rust/parser/test/mod.rs
  rust/parser/typeql.pest
  rust/pattern/conjunction.rs
  rust/pattern/constraint/mod.rs
  rust/pattern/constraint/thing/has.rs
  rust/pattern/constraint/thing/relation.rs
  rust/pattern/constraint/thing/value.rs
  rust/pattern/constraint/type_/mod.rs
  rust/pattern/constraint/type_/owns.rs
  rust/pattern/constraint/type_/plays.rs
  rust/pattern/constraint/type_/regex.rs
  rust/pattern/constraint/type_/relates.rs
  rust/pattern/constraint/type_/sub.rs
  rust/pattern/disjunction.rs
  rust/pattern/label.rs
  rust/pattern/mod.rs
  rust/pattern/negation.rs
  rust/pattern/schema/rule.rs
  rust/pattern/test/mod.rs
  rust/pattern/variable/builder/mod.rs
  rust/pattern/variable/builder/thing.rs
  rust/pattern/variable/builder/type_.rs
  rust/pattern/variable/concept.rs
  rust/pattern/variable/mod.rs
  rust/pattern/variable/thing.rs
  rust/pattern/variable/type_.rs
  rust/pattern/variable/unbound.rs
  rust/query/aggregate.rs
  rust/query/mod.rs
  rust/query/typeql_delete.rs
  rust/query/typeql_insert.rs
  rust/query/typeql_match.rs
  rust/query/typeql_undefine.rs
  rust/query/typeql_update.rs
  rust/rustfmt.toml
  rust/tests/behaviour/main.rs
  rust/typeql_lang.rs
Labels: type: feature, priority: high

#285 Fix rule validation
  rust/pattern/schema/rule.rs
Labels: type: bug, priority: high
