Repository typedb/typeql, pull requests merged in 2024-09, with the labels that each got.

#365 Expose some extra fields in statements
  rust/parser/statement/thing.rs
  rust/statement/thing/mod.rs
Labels: type: refactor

#367 Implement duration literal parsing
  WORKSPACE
  rust/parser/literal.rs
  rust/parser/statement/thing.rs
  rust/parser/typeql.pest
  rust/query/pipeline/stage/fetch.rs
  rust/query/pipeline/stage/reduce.rs
  rust/schema/definable/struct_.rs
  rust/statement/mod.rs
  rust/statement/thing/mod.rs
  rust/typeql.rs
  rust/value.rs
Labels: type: feature, priority: medium

#368 Update syntax for reduce stages in pipelines
  rust/common/token.rs
  rust/parser/pipeline.rs
  rust/parser/test/aggregate.rs
  rust/parser/test/fetch.rs
  rust/parser/test/group_aggregate.rs
  rust/parser/test/mod.rs
  rust/parser/typeql.pest
  rust/query/pipeline/stage/reduce.rs
Labels: type: feature
