Repository typedb/typeql, pull requests merged in 2024-01, with the labels that each got.

#309 Migrate artifact hosting to cloudsmith
  .factory/automation.yml
  README.md
  RELEASE_NOTES_LATEST.md
  RELEASE_TEMPLATE.md
  WORKSPACE
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/repositories.bzl
  grammar/README.md
  grammar/java/BUILD
  grammar/python/BUILD
  java/BUILD
  java/README.md
  java/builder/BUILD
  java/common/BUILD
  java/parser/BUILD
  java/pattern/BUILD
  java/query/BUILD
  java/test/deployment/pom.xml
  rust/BUILD
Labels: type: build

#310 Implement non-ascii variables in Java and Rust
  dependencies/vaticle/repositories.bzl
  grammar/TypeQL.g4
  java/TypeQL.java
  java/common/Reference.java
  java/common/exception/ErrorMessage.java
  java/parser/test/ParserTest.java
  java/pattern/constraint/ThingConstraint.java
  java/query/TypeQLFetch.java
  java/query/test/TypeQLQueryTest.java
  java/test/behaviour/typeql/TypeQLSteps.java
  rust/common/error/mod.rs
  rust/common/identifier.rs
  rust/common/mod.rs
  rust/parser/mod.rs
  rust/parser/test/mod.rs
  rust/parser/typeql.pest
  rust/pattern/label.rs
  rust/query/typeql_fetch.rs
  rust/tests/behaviour/steps.rs
  rust/variable/type_reference.rs
  rust/variable/variable.rs
Labels: type: feature, priority: medium

#311 Sync dependencies in CI
  .factory/automation.yml
Labels: type: build, priority: high
