Repository typedb/typeql, pull requests merged in 2025-01, with the labels that each got.

#386 Rename within to groupby
  rust/common/token.rs
  rust/parser/pipeline.rs
  rust/parser/test/group_aggregate.rs
  rust/parser/typeql.pest
  rust/query/pipeline/stage/reduce.rs
Labels: type: refactor, priority: medium

#389 Add 'dec' suffix to decimal literals
  rust/parser/literal.rs
  rust/parser/test/match_queries.rs
  rust/parser/typeql.pest
  rust/value.rs
Labels: type: feature, type: refactor

#390 Bump version & prepare release notes for 3.0.3
  RELEASE_NOTES_LATEST.md
  VERSION
Labels: type: build

#391 Enhance error printing and query source span availability
  rust/annotation.rs
  rust/common/error/mod.rs
  rust/common/identifier.rs
  rust/common/mod.rs
  rust/expression/mod.rs
  rust/parser/define/function.rs
  rust/parser/pipeline.rs
  rust/parser/redefine.rs
  rust/parser/test/error.rs
  rust/parser/test/fetch.rs
  rust/parser/test/match_queries.rs
  rust/pattern/mod.rs
  rust/query/pipeline/mod.rs
  rust/query/pipeline/stage/delete.rs
  rust/query/pipeline/stage/fetch.rs
  rust/query/pipeline/stage/insert.rs
  rust/query/pipeline/stage/match_.rs
  rust/query/pipeline/stage/mod.rs
  rust/query/pipeline/stage/modifier.rs
  rust/query/pipeline/stage/put.rs
  rust/query/pipeline/stage/reduce.rs
  rust/query/pipeline/stage/update.rs
  rust/query/schema/define.rs
  rust/query/schema/redefine.rs
  rust/query/schema/undefine.rs
  rust/schema/definable/function.rs
  rust/schema/definable/struct_.rs
  rust/schema/definable/type_/capability.rs
  rust/schema/definable/type_/mod.rs
  rust/schema/undefinable/mod.rs
  rust/statement/comparison.rs
  rust/statement/mod.rs
  rust/statement/thing/isa.rs
  rust/statement/thing/mod.rs
  rust/statement/type_.rs
  rust/type_.rs
  rust/value.rs
Labels: type: refactor, priority: high
